### ISSUE TITLE
no-cache matching unexpectedly

### ISSUE THREAD

**Issue by davidbirdsong** [imgix/siphon#3]
With a delimiter of `;` this string doesn't update my string index but fires a match on `no-cache`: 
`max-age=0, no-cache, no-store`

and so I get an index error for the start and end of no-cache since the end index hasn't been updated accordingly.

Just wondering how siphon would handle that string.

**Comment by kalamay** [comment]
I've added this test: https://github.com/imgix/siphon/blob/c7707c015dd847f04dba90f69c7e45c318525bb9/test/cache.c#L124-L146

The expectation is that only the `max-age`, `no-cache`, and `no-store` cache control directives are set and that the value of `max-age` is `0`. This is testing as true, but I'm not sure what the `;` delimiter would be though? Is this in an effort to support improperly encoded cache control headers? That is a common mistake, so I should probably support them here.

**Comment by kalamay** [comment]
Ok, `;` is supported: https://github.com/imgix/siphon/commit/a056042e4d18acdec596c391f98870ad0714f5fd#diff-94a38e716f9e1639d781a0086cf389ca
